ParisBakery/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ParisBakery.Models
{
  public class Treat
  {
    public Treat()
    {
      this.Flavors = new HashSet<FlavorTreat>();
    }
    public int TreatId { get; set; }
    public string Name { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:c}")]
    public float Price { get; set; }
    public ICollection<FlavorTreat> Flavors { get; }
  }
}

ParisBakery/Controllers/FlavorsController.cs
using ParisBakery.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq; 

namespace ParisBakery.Controllers
{
  public class FlavorsController: Controller

  {
    private readonly ParisBakeryContext _db;
    public FlavorsController(ParisBakeryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Flavor> flavorList = _db.Flavors.ToList();
      return View(flavorList);
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create (Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.Treats)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Admin")]
    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.FlavorId });
    }
  }
}

ParisBakery/Controllers/TreatsController.cs
using ParisBakery.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace ParisBakery.Controllers
{
  public class TreatsController : Controller
  {
    private readonly ParisBakeryContext _db;
    public TreatsController(ParisBakeryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Treat> treatList = _db.Treats.ToList();
      return View(treatList);
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.Flavors)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize(Roles = "Admin")]
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "Admin")]
    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Type");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TreatId });
    }
  }
}

ParisBakery/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model ParisBakery.Models.Treat;

<br>
<div class="card custom-card">
  <div class="card-header">
    <h1>Add a Flavor for @Html.DisplayFor(model => model.Name)</h1>
  </div>

@using (Html.BeginForm())
{
  <div class="card-body">
    <div class="form-group">
      @Html.HiddenFor(model => model.TreatId)
      
      @Html.Label("Add Flavor")
      @Html.DropDownList("FlavorId")
    </div>
  </div>
  <div class="card-footer">
      <input type="submit" value="Save" class="btn btn-outline-primary" />
      @Html.ActionLink("Back to details", "Details", new { id = Model.TreatId }, new { @class="btn btn-outline-primary" })
  </div>
}
</div>

ParisBakery/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model ParisBakery.Models.Treat;

<br>
<div class="card custom-card">
  <div class="card-header">
    <h1 class="display-4">Add a new Treat</h1>
  </div>
  @using (Html.BeginForm())
  {
    <div class="card-body">
      <div class="form-group">
        @Html.Label("Name of Treat:")
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Name of Product"})
      </div>
      <div class="form-group">
        @Html.Label("Price:")
        @Html.TextBoxFor(model => model.Price, new { @class = "form-control", type = "number", step = "0.01", max = "1000.00", placeholder = "Amount", required = "required" })
      </div>
    </div>
    <div class="card-footer">
      <input type="submit" value="Add new Treat" class="btn btn-outline-primary" />
    </div>
  }
</div>

ParisBakery/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ParisBakery.Models.Treat;

<br>
<div class="card custom-card">
  <div class="card-header">
    <h1 class="display-4">Delete @Html.DisplayFor(model => model.Name)</h1>
  </div>
  <div class="card-body">
    <p>Confirm Delete?</p>
  </div>
  @using (Html.BeginForm())
  {
    <div class="card-footer">
      <input type="submit" value="Delete" class="btn btn-outline-danger" />
      @Html.ActionLink("Back to details", "Details", new { id = Model.TreatId }, new { @class="btn btn-outline-primary" })
    </div>
  }

ParisBakery/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model ParisBakery.Models.Treat;

<br>
<div class="card custom-card">
  <div class="card-header">
    <h1>@Html.DisplayFor(model => model.Name)</h1>
    <p>Price: @Html.DisplayFor(model => model.Price)</p>
  </div>
  <div class="card-body">
    @if(@Model.Flavors.Count == 0)
    {
      <h3 class="card-title">Flavors:</h3>
      <p>There are no Treats with this flavor!</p>
    }
    else
    {
      <h3 class="card-title"><strong>Flavor(s): </strong></h3>
      <ul class="list-group" align="center">
      @foreach(var join in Model.Flavors)
      {
        <li class="list-group-item text-dark">@Html.ActionLink($"{ join.Flavor.Type }", "Details", "Flavors", new { id = join.Flavor.FlavorId })
        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
          @using (@Html.BeginForm("DeleteFlavor", "Treats"))
          {
            @Html.Hidden("joinId", @join.FlavorTreatId)
            <input type="submit" value="Delete" class="btn btn-outline-danger"/>
          }
        }
        </li>
      }
      </ul>
    }
  </div>
  @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
  {
    <div class="card-footer">
      @Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId }, new { @class="btn btn-outline-primary" })
      @Html.ActionLink("Edit this Treat", "Edit", new { id = Model.TreatId }, new { @class="btn btn-outline-primary" })
      @Html.ActionLink("Delete this Treat", "Delete", new { id = Model.TreatId }, new { @class="btn btn-outline-primary" })
    </div>
  }
  else if (User.Identity.IsAuthenticated)
  {
    <div class="card-footer">
      <button href="#" class="btn btn-outline-secondary">Add to Order</button>
    </div>
  }
</div>

ParisBakery/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ParisBakery.Models.Treat;

<br>
<div class="card custom-card">
  <div class="card-header">
    <h1 class="display-4">Edit @Html.DisplayFor(model => model.Name)</h1>
  </div>
  @using (Html.BeginForm())
  {
    <div class="card-body">
      <div class="form-group">
        @Html.HiddenFor(model => model.TreatId)
      
        @Html.Label("Type of Treat:")
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Name of Product" })
      </div>
      <div class="form-group">
        @Html.Label("Price:")
        @Html.TextBoxFor(model => model.Price, new { @class = "form-control", type = "number", step = "0.01", max = "100000.00", placeholder = "Amount", required = "required" })
      </div>
    </div>
    <div class="card-footer"> 
      <input type="submit" value="Save" class="btn btn-outline-primary" />
      @Html.ActionLink("Back to details", "Details", new { id = Model.TreatId }, new { @class="btn btn-outline-primary" })
    </div>
  }
</div>

ParisBakery/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using ParisBakery.Models;
@model List<ParisBakery.Models.Treat>

<br>
<div class="card custom-card">
  <div class="card-header">
    <h1>Treats:</h1>
  </div>
  <div class="card-body">
    @if(@Model.Count == 0)
    {
      <h3>There are no treats here.</h3>
    }

    @foreach (Treat treat in Model)
    {
      <ul class="list-group" align="center">
        <li class="list-group-item list-group-item-action text-dark">@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
      </ul>
    }
  </div>
  @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
  {
    <div class="card-footer">
      @Html.ActionLink("Add a new Treat", "Create", "Treats", null, new { @class="btn btn-outline-primary" })
    </div>
  }
</div>